### ISSUE TITLE
Write distribution of NOVA filesystem

### ISSUE THREAD

**Issue by pratham-pc** [NVSL/linux-nova#79]
Is there any way to know how the writes are being distributed?
Any of the two - the expected writes and the writes which actually take place because of the caching system.

**Comment by pratham-pc** [comment]
@Andiry if it is possible, can you please check this?

**Comment by Andiry** [comment]
There is no caching system in NOVA (if you mean DRAM cache). For the writes, since the NVM pages are allocated across the CPUs based on physical address, depending on which core handling the write request, writes will be performed on the free pages that is managed by that core, starting from low address. If data fault protection is enabled, things are more complicated because parity will be written to a different place. But that is the basic idea.
